### ISSUE TITLE
external contributions?

### ISSUE THREAD

**Issue by monperrus** [jentfoo/JunitLite#1]
are you interested in external contributions or should I fork this very interesting project?

**Comment by jentfoo** [comment]
I would be happy to continue to maintain this project and bring in external contributions.

@monperrus would you mind explaining why this is useful to you?  Is it for working with avian?  The reason I originally built this was so I could run external projects (ie my threadly project's) unit tests under the avian classpath to ensure there is no unexpected interactions.

The only reason I have not developed this further is because I did not expect many other people having similar needs.

**Comment by monperrus** [comment]
> @monperrus https://github.com/monperrus would you mind explaining
> why this is useful to you? Is it for working with avian?
> yes

--Martin

**Comment by jentfoo** [comment]
Sounds good to me.  I can help on both ends (this library as well as if avian classpath expansions end up being needed).

Just go ahead and file issues and submit pull requests like you normally would.
